//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACC_EMP_Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACC_EMP_Employee()
        {
            this.HRS_SAL_Salaries = new HashSet<HRS_SAL_Salaries>();
            this.HRS_EMC_EmpContract = new HashSet<HRS_EMC_EmpContract>();
        }
    
        public int ACC_EMP_ID { get; set; }
        public int ACC_EMP_Number { get; set; }
        public string ACC_EMP_Name { get; set; }
        public string ACC_EMP_Name2 { get; set; }
        public Nullable<int> ACC_EMP_JOBID { get; set; }
        public string ACC_EMP_Address { get; set; }
        public Nullable<int> ACC_EMP_MartialStatus { get; set; }
        public System.DateTime ACC_EMP_DateofBirth { get; set; }
        public string ACC_EMP_PlaceofBirth { get; set; }
        public Nullable<int> ACC_EMP_documentNum { get; set; }
        public Nullable<int> ACC_EMP_Gender { get; set; }
        public System.DateTime ACC_EMP_JoinDate { get; set; }
        public Nullable<int> ACC_EMP_WSTID { get; set; }
        public Nullable<System.DateTime> ACC_EMP_EntryDate { get; set; }
        public Nullable<System.DateTime> ACC_EMP_UpdatedDate { get; set; }
        public Nullable<System.DateTime> ACC_EMP_DeleteDate { get; set; }
        public bool ACC_EMP_IsDelete { get; set; }
    
        public virtual JOB_JOBS JOB_JOBS { get; set; }
        public virtual WST_WorkStatus WST_WorkStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRS_SAL_Salaries> HRS_SAL_Salaries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRS_EMC_EmpContract> HRS_EMC_EmpContract { get; set; }
    }
}
