//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEP_Departments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DEP_Departments()
        {
            this.DEP_Departments1 = new HashSet<DEP_Departments>();
            this.ACC_EMP_Employee = new HashSet<ACC_EMP_Employee>();
        }
    
        public int DEP_ID { get; set; }
        public Nullable<int> DEP_ParentID { get; set; }
        public int DEP_Number { get; set; }
        public string DEP_Name { get; set; }
        public string DEP_Name2 { get; set; }
        public string DEP_Email { get; set; }
        public string DEP_Phone { get; set; }
        public string DEP_Shortcut { get; set; }
        public Nullable<System.DateTime> DEP_EntryDate { get; set; }
        public Nullable<System.DateTime> DEP_UpdateDate { get; set; }
        public Nullable<System.DateTime> DEP_DeleteDate { get; set; }
        public bool DEP_IsDelete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEP_Departments> DEP_Departments1 { get; set; }
        public virtual DEP_Departments DEP_Departments2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACC_EMP_Employee> ACC_EMP_Employee { get; set; }
    }
}
