//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXWebApplication.Models
{
    using System;
    using System.Collections.Generic;
 
    public partial class HRS_EMC_EmpContract
    {
        public int HRS_EMC_ID { get; set; }
        public int HRS_EMC_Number { get; set; }
        public System.DateTime HRS_EMC_Startdate { get; set; }
        public Nullable<System.DateTime> HRS_EMC_Enddate { get; set; }
        public int HRS_EMC_EmpID { get; set; }
        public int HRS_EMC_Action { get; set; }
        public Nullable<int> HRS_EMC_IssueNum { get; set; }
        public Nullable<System.DateTime> HRS_EMC_Issuedate { get; set; }
        public string HRS_EMC_Desc { get; set; }
        public System.DateTime HRS_EMC_Entrydate { get; set; }
        public Nullable<System.DateTime> HRS_EMC_Updatedate { get; set; }
        public Nullable<System.DateTime> HRS_EMC_DeleteDate { get; set; }
        public bool HRS_EMC_IsDeleted { get; set; }
    
        public virtual ACC_EMP_Employee ACC_EMP_Employee { get; set; }
    }
}
