//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRS_SAL_Salaries
    {
        public int HRS_SAL_ID { get; set; }
        public int HRS_SAL_EMPID { get; set; }
        public decimal HRS_SAL_SalaryAmount { get; set; }
        public System.DateTime HRS_SAL_StartDate { get; set; }
        public Nullable<System.DateTime> HRS_SAL_EndDate { get; set; }
        public System.DateTime HRS_SAL_EntryDate { get; set; }
        public System.DateTime HRS_SAL_UpdateDate { get; set; }
        public System.DateTime HRS_SAL_DeleteDate { get; set; }
        public bool HRS_SAL_IsDelete { get; set; }
    
        public virtual ACC_EMP_Employee ACC_EMP_Employee { get; set; }
    }
}
